# -- Site Information --
title: Hugo Bootstrapped
languageCode: en-us
baseURL: https://skrillx13.github.io/Hugo-Bootstrapped/

# -- Markup Configuration --
markup:
  goldmark:
    renderer:
      unsafe: true

# -- Chroma Configuration --
highlight:
  enabled: true
  theme: "monokai"
  noClasses: false

# -- URL Configuration --
relativeURLs: true
canonifyURLs: true
